development:
  tmdb_key: <%= ENV["TMDB_KEY"] %>
  mailchimp_key: <%= ENV["MAILCHIMP_KEY"] %>

test:
  tmdb_key: <%= ENV["TMDB_KEY"] %>
  mailchimp_key: <%= ENV["MAILCHIMP_KEY"] %>

production:
  tmdb_key: <%= ENV["TMDB_KEY"] %>
  mailchimp_key: <%= ENV["MAILCHIMP_KEY"] %>
